hydra:
  job:
    chdir: False

train:
  dataset_name: ["JasiekKaczmarczyk/maestro-v1-sustain-masked"] # huggingface dataset
  batch_size: 168
  num_workers: 8
  lr: 1e-5
  weight_decay: 0.01
  pitch_shift_probability: 0.5
  time_stretch_probability: 0.5
  num_epochs: 5
  device: "cuda"
  precision: "16-mixed" # not implemented yet
  overfit_single_batch: False
  use_gradnorm: True
  gn_restoring_force: 1.5
  masking_ratio_scheduler:
    0: 0.15
    6e7: 0.2
    12e7: 0.25
    18e7: 0.3
    24e7: 0.35
    30e7: 0.4
    36e7: 0.45
    42e7: 0.5
  loss_lambdas:
    pitch: 1.
    velocity: 1.
    start: 1.
    duration: 1.


model:
  encoder_dim: 768
  encoder_depth: 12
  encoder_num_heads: 12
  decoder_dim: 512
  decoder_depth: 8
  decoder_num_heads: 16
  mlp_ratio: 4.
  dynamics_embedding_depth: 4

paths:
  save_ckpt_dir: "checkpoints" # directory where checkpoints will be saved
  load_ckpt_path: null # if not None, specifies path to model state dict which will be loaded
  log_dir: "logs"
  hf_repo_id: null # repo id to upload model to huggingface if null model is not uploaded

logger:
  run_name: midi-masked-autoencoder-${now:%Y-%m-%d-%H-%M}
  log_every_n_steps: 50
